const products = [{"id": 1, "name": "Lip Kit - Cherry Red", "price": 24.0, "img": "images/product1.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 2, "name": "Cherry Blush", "price": 28.0, "img": "images/product2.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 3, "name": "Black Cherry Eyeliner", "price": 19.0, "img": "images/product3.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 4, "name": "Liquid Lipstick - Velvet", "price": 22.0, "img": "images/product4.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 5, "name": "Radiant Highlighter", "price": 30.0, "img": "images/product5.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 6, "name": "Cherry Lip Gloss", "price": 18.0, "img": "images/product6.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 7, "name": "Cherry Eyeshadow Palette", "price": 45.0, "img": "images/product7.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 8, "name": "Soft Bronzer", "price": 26.0, "img": "images/product8.png", "desc": "High-quality product inspired by the Cherry Collection."}, {"id": 9, "name": "Precision Pencil Liner", "price": 14.0, "img": "images/product9.png", "desc": "High-quality product inspired by the Cherry Collection."}];

const container = document.getElementById('products-container');
function renderProducts(){ container.innerHTML=''; products.forEach(p=>{ const el=document.createElement('div'); el.className='product'; el.innerHTML=`<img src="${p.img}" alt="${p.name}"><h4>${p.name}</h4><p class="price">$${p.price.toFixed(2)}</p><div class="btns"><button onclick="openModal(${p.id})">View Details</button><button onclick="addToCartId(${p.id})">Add to Cart</button></div>`; container.appendChild(el); }); }
function openModal(id){ const p=products.find(x=>x.id===id); document.getElementById('modal-img').src=p.img; document.getElementById('modal-title').textContent=p.name; document.getElementById('modal-price').textContent='$'+p.price.toFixed(2); document.getElementById('modal-desc').textContent=p.desc; document.getElementById('product-modal').classList.remove('hidden'); }
function addToCart(name,price,img){ let cart=JSON.parse(localStorage.getItem('cart')||'[]'); cart.push({name,price,img}); localStorage.setItem('cart',JSON.stringify(cart)); document.getElementById('cart-count').textContent=cart.length; alert(name+' added to cart'); }
function addToCartId(id){ const p=products.find(x=>x.id===id); addToCart(p.name,p.price,p.img); }
document.getElementById('shop-now').addEventListener('click',()=>{ document.querySelector('#shop').scrollIntoView({behavior:'smooth'}); });
renderProducts();
